# Generated by Django 3.1.4 on 2020-12-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
